# Generated by Django 4.2.6 on 2023-11-05 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_movieinfo_summary_remove_movieinfo_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieInfo',
            new_name='LanguageInfo',
        ),
    ]
