# Generated by Django 4.2.6 on 2023-11-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_languageinfo_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageinfo',
            name='os',
            field=models.CharField(max_length=100),
        ),
    ]
