# Generated by Django 4.2.6 on 2023-11-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_languageinfo_os'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageinfo',
            name='designed_by',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='languageinfo',
            name='developer',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='languageinfo',
            name='year',
            field=models.IntegerField(default='0'),
        ),
    ]
